export {default as Home} from './Home'
export {default as About} from './About'
export {default as Events} from './Events'
export {default as Contact} from './Contact'
export {default as Literature} from './Literature'
export {default as Magazine} from './Magazine'
export {default as Team} from './Team'